### ISSUE TITLE
ImportError when importing Tkinter

### ISSUE THREAD

**Issue by crappy123** [niranjanreddy891/tkinter#1]
I got error on win-10 64 bit. Pls help me in this issue.

**Comment by niranjanreddy891** [comment]
Which version of Python are you using?

**Comment by palkinjuneja** [comment]
if you are using version 3.6 using 't' in place of 'T' i.e import Tkinter else if version 2.6 or less use Tkinter, there is a change of capitalization in some versions.

**Comment by niranjanreddy891** [comment]
Try this 
```
try:
    # for Python2.7
    from Tkinter import *
except ImportError:
    # for Python3
    from tkinter import *
```
I hope it works

**Comment by crappy123** [comment]
@niranjanreddy891, thanks. Now it works for me. You saved my day. :)
The code snippet which @niranjanreddy891 provided is awesome since it works for both versions of python. Nice usage of exceptions. You are great man.

**Comment by niranjanreddy891** [comment]
Nice. Since it is working fine, I am closing the issue. If you encounter any problem don't mind to raise an issue. :)

**Comment by niranjanreddy891** [comment]
@palkinjuneja, thanks for helping him.
